// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Prisma CLI loads this config for every command, including `prisma generate`
 * (postinstall). Do not throw here — generate does not need a live DB.
 *
 * For migrate/db push prefer DIRECT_URL: Supabase transaction pooler (:6543)
 * hangs on advisory locks. Runtime still uses DATABASE_URL via PrismaPg.
 */
function cliDatabaseUrl() {
  return (
    process.env.DIRECT_URL?.trim() ||
    process.env.DATABASE_URL?.trim() ||
    // Placeholder so `prisma generate` works when env is not injected yet.
    "postgresql://prisma:prisma@127.0.0.1:5432/prisma?schema=public"
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: cliDatabaseUrl(),
  },
});
