// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Prisma CLI (migrate/db push) must use a direct Postgres connection.
 * Supabase transaction pooler (:6543) hangs on advisory locks during migrate.
 * Runtime app code keeps using DATABASE_URL (pooled) via PrismaPg adapter.
 */
function migrationDatabaseUrl() {
  const direct = process.env.DIRECT_URL?.trim();
  const databaseUrl = process.env.DATABASE_URL?.trim();
  const url = direct || databaseUrl;

  if (!url) {
    throw new Error("DATABASE_URL (or DIRECT_URL) is required for Prisma CLI.");
  }

  if (!direct && /:6543\b/.test(url) && /pooler\.supabase\.com/i.test(url)) {
    throw new Error(
      "DATABASE_URL points at Supabase transaction pooler (:6543). " +
        "Set DIRECT_URL to the direct DB URL (db.<project>.supabase.co:5432) " +
        "or the session pooler (:5432) for prisma migrate deploy.",
    );
  }

  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationDatabaseUrl(),
  },
});
